# GitHub Actions for PostGIS
#
# Paul Ramsey <pramsey at cleverelephant dot ca>

name: "CI"
on: [push, pull_request]

jobs:
  linux:

    runs-on: ubuntu-latest

    name: "CI"
    strategy:
      matrix:
        ci:
        - { PGVER: 13 }
        - { PGVER: 14 }
        - { PGVER: 15 }
        - { PGVER: 16 }
        - { PGVER: 17 }
        - { PGVER: 18 }

    steps:

    - name: 'Check Out'
      uses: actions/checkout@v3

    - name: 'Install PostgreSQL'
      run: |
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg-snapshot main ${{ matrix.ci.PGVER }}" > /etc/apt/sources.list.d/pgdg.list'
        curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg >/dev/null
        sudo apt-get update
        sudo apt-get -y install -t $(lsb_release -cs)-pgdg-snapshot
        sudo apt-get -y install postgresql-${{ matrix.ci.PGVER }} postgresql-server-dev-${{ matrix.ci.PGVER }} postgresql-client-${{ matrix.ci.PGVER }}

    - name: 'Install Curl'
      run: |
        sudo apt-get -y install libcurl4-gnutls-dev

    - name: 'Start PostgreSQL'
      run: |
        export PGDATA=/var/lib/postgresql/${{ matrix.ci.PGVER }}/main
        export PGETC=/etc/postgresql/${{ matrix.ci.PGVER }}/main
        export PGBIN=/usr/lib/postgresql/${{ matrix.ci.PGVER }}/bin
        # needed for pg18 and above cause cluster is no longer created on install
        if [ ! -d "/etc/postgresql/${{ matrix.ci.PGVER }}/main" ]; then
           sudo pg_createcluster ${{ matrix.ci.PGVER }} main
        fi       
        sudo cp ./ci/pg_hba.conf $PGETC/pg_hba.conf
        sudo su postgres -c "$PGBIN/pg_ctl --pgdata $PGDATA start -o '-c config_file=$PGETC/postgresql.conf -p 5432'"

    - name: 'Start HttpBin Docker'
      run: |
        docker run -d -p 9080:80 kennethreitz/httpbin

    - name: 'Build & Test'
      run: |
        export PATH=/usr/lib/postgresql/${{ matrix.ci.PGVER }}/bin/:$PATH
        export PG_CONFIG=/usr/lib/postgresql/${{ matrix.ci.PGVER }}/bin/pg_config
        export PG_CFLAGS=-Werror
        make
        sudo -E make PG_CONFIG=$PG_CONFIG install
        PGUSER=postgres make installcheck || (cat regression.diffs && /bin/false)

